"""add task fields

Revision ID: 5b14a9abbf23
Revises: adb42cfeb292
Create Date: 2026-04-10 14:41:21.258064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b14a9abbf23'
down_revision: Union[str, Sequence[str], None] = 'adb42cfeb292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'manager_id')
    # ### end Alembic commands ###
