"""add time_estimate to history

Revision ID: 83f036312410
Revises: 551ef01fefeb
Create Date: 2026-04-14 18:41:37.855712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f036312410'
down_revision: Union[str, Sequence[str], None] = '551ef01fefeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('old_time_estimate', sa.Integer(), nullable=True))
    op.add_column('task_history', sa.Column('new_time_estimate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'new_time_estimate')
    op.drop_column('task_history', 'old_time_estimate')
    # ### end Alembic commands ###
