"""add developer_id column

Revision ID: fa9133e42e2b
Revises: 9438c4b89d52
Create Date: 2026-04-09 20:14:30.817829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9133e42e2b'
down_revision: Union[str, Sequence[str], None] = '9438c4b89d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['developer_id'], ['id'])
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'users', ['assigned_to'], ['id'])
    op.drop_column('tasks', 'developer_id')
    # ### end Alembic commands ###
